### ISSUE TITLE
[bug]: Browser build is used in CF workers environment

### ISSUE THREAD

**Issue by remihuigen** [algolia/algoliasearch-client-javascript#1548]
### Description

After migrating from v4 to v5 (which was confusing in itself, as others have mentioned), I'm encountering weird issues with the algolia client in production. Such as: ``algolia.generateSecuredApiKey is not a function`` or ``ReferenceError: XMLHttpRequest is not defined``

I did some digging in the output of the production build, and noticed:

```
// .wrangler/tmp/chunks/_/algolia.mjs

function algoliasearch(appId, apiKey, options) {
    return {
        ...searchClient(appId, apiKey, {
            timeouts: {
                connect: DEFAULT_CONNECT_TIMEOUT_BROWSER$3,
                read: DEFAULT_READ_TIMEOUT_BROWSER$3,
                write: DEFAULT_WRITE_TIMEOUT_BROWSER$3,
            },
            requester: createXhrRequester(),
            algoliaAgents: [{ segment: 'Browser' }],
            authMode: 'WithinQueryParameters',
            responsesCache: createMemoryCache$3(),
            requestsCache: createMemoryCache$3({ serializable: false }),
            hostsCache: createFallbackableCache$3({
                caches: [createBrowserLocalStorageCache$3({ key: `${apiClientVersion}-${appId}` }), createMemoryCache$3()],
            }),
            ...options,
        }),
        /**
         * And other methods from the full client, not relevant to this issue
        */
    };
}

```

Apparently the browser build is used, and not the node js build. But I can't figure why this is happening...

I'm using a Nitro server in a CF workers environment. Version of Algolia client is 5.2.5, but it's been having this issue since at least 5.2.1

for context, this is how the client is set up 👇
```
// utils/algolia.ts
import { algoliasearch } from "algoliasearch";
export const useSearch = (opt: { session: Session}) => {
    const { appId, publicKey } = useRuntimeConfig().algoliaSearch.onderwijsloket
    const client = algoliasearch(
        appId,
        opt.session?.algolia?.apiKey ? opt.session.algolia.apiKey : publicKey,
        {
            baseHeaders: {
                'X-Algolia-UserToken':  opt.session?.itemId || 'anonymous',
            }
        }
    )
    
    return client
}
```

### Client

All

### Version

5.2.5

**Comment by shortcuts** [comment]
Hey! Thanks for reporting and keeping up with the upgrade :)

Looking at https://developers.cloudflare.com/workers/wrangler/bundling/#conditional-exports everything looks correctly defined in [our exports](https://github.com/algolia/algoliasearch-client-javascript/blob/main/packages/algoliasearch/package.json#L18), but it seems to in the end fallback to our default field, which should be used for browser only

was it working on v4? maybe it used one of the root fields https://github.com/algolia/algoliasearch-client-javascript/blob/v4/packages/algoliasearch/package.json#L12

**Comment by remihuigen** [comment]
@shortcuts I'm not 100% sure it was working in v4, since I haven't done a production build with v4.

Primary reason for that was algolia/api-clients-automation#3608

If you really need to know if v4 was working I could find out, but that would take some effort / time

**Comment by shortcuts** [comment]
> @shortcuts I'm not 100% sure it was working in v4, since I haven't done a production build with v4.

Thanks for letting me know!

> If you really need to know if v4 was working I could find out, but that would take some effort / time

No worries it's not necessary, it could just have gave hints on how to resolve the issue

---

One workaround here could be to import algoliasearch node directly: `algoliasearch/dist/node` or the cjs version if esm isn't supported `algoliasearch/dist/node.cjs`

**Comment by Haroenv** [comment]
I believe you should use the fetch requester, which isn't used in any build by default in v4 or v5

**Comment by remihuigen** [comment]
as in 

```
import { searchClient } from "@algolia/client-search";
import { createFetchRequester } from "@algolia/requester-fetch";

const client = searchClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", {
  requester: createFetchRequester(),
});
```

**Comment by remihuigen** [comment]
@Haroenv ``createFetchRequester`` only mitigates part of the problem, so that i can send search queries... The root cause (i.e. using browser build) is not solved.

For example; I still can't use the ``generateSecuredApiKey`` method, since this is not present in the browser build (i think?)

```
// .wrangler/tmp/chunks/_/algolia.mjs

function algoliasearch(appId, apiKey, options) {
    return {
        ...searchClient(appId, apiKey, {
            timeouts: {
                connect: DEFAULT_CONNECT_TIMEOUT_BROWSER$3,
                read: DEFAULT_READ_TIMEOUT_BROWSER$3,
                write: DEFAULT_WRITE_TIMEOUT_BROWSER$3,
            },
            requester: c(),                                                // this used to be createXhrRequester()
            algoliaAgents: [{ segment: 'Browser' }],                       // Still using browser build
            authMode: 'WithinQueryParameters',
            responsesCache: createMemoryCache$3(),
            requestsCache: createMemoryCache$3({ serializable: false }),
            hostsCache: createFallbackableCache$3({
                caches: [createBrowserLocalStorageCache$3({ key: `${apiClientVersion}-${appId}` }), createMemoryCache$3()],
            }),
            ...options,
        }),
        /**
         * And other methods from the full client, not relevant to this issue
        */
    };
}
```

**Comment by shortcuts** [comment]
Hey, I'm releasing the 5.4.0 which provides a new `worker` exports field. Tested on `miniflare` is seems to resolve the module correct, let me know if it's not the case :)

**Comment by remihuigen** [comment]
@shortcuts Yup, module now resolves to the node build! It did introduce a new TS error though

```
Property 'generateSecuredApiKey' does not exist on type 'Algoliasearch'.ts(2339)
```

It also brought me back to the issue I started out with two weeks ago ``[unenv] crypto.createHmac is not implemented yet!``, which was resolved with https://github.com/algolia/api-clients-automation/pull/3608 in 5.2.2, but reintroduced in 5.4.0 🤔

**Comment by shortcuts** [comment]
Could you please provide a minimal reproductive example? I've tried my best with [vitest and miniflare here](https://github.com/algolia/api-clients-automation/pull/3689) but it seems to work 🤔

**Comment by remihuigen** [comment]
I'll check downstream first. I'll circle back if there is no solution there. 

Thanks though!

**Comment by si1k** [comment]
I am having this issue as well for v5.4.0 when trying to deploy to a Firebase function. 

`Property 'generateSecuredApiKey' does not exist on type 'Algoliasearch'.ts(2339)`

```
import { algoliasearch } from 'algoliasearch';
...
const client = algoliasearch(appId.value(), writeApiKey.value());
const validUntil = Math.floor(Date.now() / 1000) + 3600; // 1 hour
const publicKey = client.generateSecuredApiKey({
  parentApiKey: searchKey.value(),
  restrictions: {
    validUntil,
  },
});
```

**Comment by shortcuts** [comment]
Seems like it firebase resolves to a browser build too rather than the node one 🤔 Does it solves the issue when using `import { algoliasearch } from "algoliasearch/dist/node"`? I'll check their docs if they recommend anything

**Comment by shortcuts** [comment]
> @shortcuts, You responded as I was deleting my comment (thank you!) since using `"moduleResolution": "Bundler"` in my tsconfig.json was the issue on my end.

Ahhh good to know you resolved your issue then!

**Comment by ayuhito** [comment]
Hi @shortcuts, sorry to ping you here. Was `algoliasearch/lite` intended to be part of the fix? 

I just migrated to `v5` for Worker support and using the lite client does return the same `ReferenceError: XMLHttpRequest is not defined` errors.

```js
import { algoliasearch } from 'algoliasearch'; // Works and what I'm currently using as a workaround!
import { liteClient as algoliasearch } from 'algoliasearch/lite'; // Doesn't work
```

**Comment by kvkenyon** [comment]
I'm getting Property 'generateSecuredApiKey' does not exist on type 'Algoliasearch'. in 5.6.1 using nextjs. Any ideas? When I run the code it works just my builds are failing in production.
